defaults:
 - default_nlp

model_name_or_path: "meta-llama/Llama-3.1-8B"
trust_remote_code: True
use_auth_token: True 
load_pretrained_model: True
cache_dir: /leonardo_work/IscrB_Decentro/rzaccone/huggingface/models
_torch_dtype: torch.float32